name: dnsjava CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, windows-latest ]
        java: [ '8', '11', '17' ]
        arch: [ 'x86', 'x64' ]
        exclude:
          - os: ubuntu-18.04
            arch: x86
          - os: ubuntu-20.04
            arch: x86

    name: Java ${{ matrix.java }}/${{ matrix.arch }}/${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.arch }}
          distribution: temurin
          cache: gradle

      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Run codecovc
        if: "${{ matrix.arch == 'x64' && matrix.os == 'ubuntu-20.04' && matrix.java == '11' }}"
        uses: codecov/codecov-action@v2
